### ISSUE TITLE
My Script might be of some use for RedSand 

### ISSUE THREAD

**Issue by DRFTA** [redcode-labs/RedSand#1]
Feel free to use it, change it or adapt it for RedSand if you want [https://github.com/DRFTA/Sandbox-auto-app-installer](url)

**Comment by unrooted** [comment]
Hello, thanks for your issue. 

Nice script of yours, I can make a pwsh to add it to our project. 

Will ping you as soon as I do so.

**Comment by unrooted** [comment]
Thanks a lot for your suggestion. I allowed myself to change it a bit.
As of 0c9f72de432c69e8fb6d1a481fe1a8616eb37e69 I've added a script which will install both choco and scoop, with no pre-defined apps to install. I think I'll leave this as it is for now, and keep it for user to decide what to install.

I also turn Developer Mode by default, as added to the `setup.ps1` script.

Thanks a lot again for your suggestion. Have a great day.
